---
title: "Onboarding PWA Otomoto PL - A/B Test Evaluation 2nd iteration"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# ###################################################################################
#' Focus on OKR especially conversion on day zero
#' Test users that did "home" vs users entered onboarding ("welcome_screen")          
# ###################################################################################


```{r}
setwd("~/Verticals-bi/scripts/r/3.Analysis/CARS-6440.OnboardingTestPWA_PL")

```

# Queries for OKR2
```{r}
library(RMixpanel)
## Auth Otomoto PL
oto_auth <- mixpanelCreateAccount("otomoto.pl",
                                 token="b2b9c69bb88736c7e833e9d609004e6a",
                                 secret="ed06fd545816f0ef5c79f4936e603870", key="" 
)

## Daterange
from_date <- "20180509"
to_date <- "20180516"


# original - homepage
## to query "make_lead" custom event use: # $custom_event:750077 as per chrome console
df_lead_pl_a <- as.data.frame(
  mixpanelGetRetention(oto_auth, 
                       segment_method= "first", 
                       retention_type= "birth", 
                       born_event="home", 
                       born_where= 'number(properties["cl"]) == 1 and (string(properties["platform"]) == "rwd")', 
                       event="$custom_event:750077",
                       from=from_date, to=to_date, unit="day", intervalCount = 15 
  )
)    
  

# variation B1 - pwa
## 2nd onboarding version starting with welcome_screen with UX optimizazions
## "onboarding_experiment":"B1"
## 
df_lead_pl_b1 <- as.data.frame(
  mixpanelGetRetention(oto_auth, 
                       segment_method= "first", 
                       retention_type= "birth", 
                       born_event="welcome_screen", 
                       born_where= '"B1" in (properties["onboarding_experiment"]) ', 
                       event="$custom_event:750077",
                       from=from_date, to=to_date, unit="day", intervalCount = 15 
  )
)  
  

# variation C1 - pwa
## 2nd onboarding version starting with welcome_screen with UX optimizazions but removing segments
## "onboarding_experiment":"C1"
## 
df_lead_pl_c1 <- as.data.frame(
  mixpanelGetRetention(oto_auth, 
                       segment_method= "first", 
                       retention_type= "birth", 
                       born_event="welcome_screen", 
                       born_where= '"C1" in (properties["onboarding_experiment"]) ', 
                       event="$custom_event:750077",
                       from=from_date, to=to_date, unit="day", intervalCount = 15 
  )
)
  

```

# Calculate samples
```{r}
pop_a<- sum(df_lead_pl_a$cohortCount)
pop_b1<- sum(df_lead_pl_b1$cohortCount)
pop_c1<- sum(df_lead_pl_c1$cohortCount)

suc_a<- sum(df_lead_pl_a$retainCount.0)
suc_b1<- sum(df_lead_pl_b1$retainCount.0)
suc_c1<- sum(df_lead_pl_c1$retainCount.0)
```


# Test b1 vs original ---------------------------------------------------------
```{r cars}
dfOnboarding <-
    data.frame(
        id = c("01", "02"),
        name = c("b1", "a"),
        period = c("1st week", "1st week"),
        PopulationMetric = c("new_users","new_users"),
        PopulationValue = c(pop_b1, pop_a),
        SucessMetric = c("okr_2_same_day","okr_2_same_day"),
        SucessValue = c(suc_b1, suc_a)
    )

dfOnboarding$ctr <- 
    dfOnboarding$SucessValue / dfOnboarding$PopulationValue
```

# Power analysis
```{r}
testResultsOnboarding <- 
    power.prop.test(
        n = dfOnboarding$PopulationValue, 
        p1 = dfOnboarding$ctr[1],
        p2 = dfOnboarding$ctr[2],
        sig.level = 0.05,
        alternative = "two.sided"
    )

testResultsOnboarding
```

When considering only the same day, variation is - 17% below original. It's NOT significant yet.
```{r}
(testResultsOnboarding$p2 - testResultsOnboarding$p1) / testResultsOnboarding$p1
```


# Test c1 vs original ---------------------------------------------------------
```{r cars}
dfOnboarding <-
    data.frame(
        id = c("01", "02"),
        name = c("c1", "a"),
        period = c("1st week", "1st week"),
        PopulationMetric = c("new_users","new_users"),
        PopulationValue = c(pop_c1, pop_a),
        SucessMetric = c("okr_2_same_day","okr_2_same_day"),
        SucessValue = c(suc_c1, suc_a)
    )

dfOnboarding$ctr <- 
    dfOnboarding$SucessValue / dfOnboarding$PopulationValue
```

# Power analysis
```{r}
testResultsOnboarding <- 
    power.prop.test(
        n = dfOnboarding$PopulationValue, 
        p1 = dfOnboarding$ctr[1],
        p2 = dfOnboarding$ctr[2],
        sig.level = 0.05,
        alternative = "two.sided"
    )

testResultsOnboarding
```

Variation is - 13% below original. It's NOT significant yet.
```{r}
(testResultsOnboarding$p2 - testResultsOnboarding$p1) / testResultsOnboarding$p1
```



<!-- # ################################################################################################ -->
<!-- # OKR 2: -->
<!-- # Increase % of new users with 1+ reply after 14 days by 10% -->
<!-- # ################################################################################################ -->


<!-- # ############################################################################## -->
<!-- # 2nd week -------------------------------------------------------------------- -->
<!-- # Mon 27 Nov - Sun 03 Dic  -->
<!-- ## because we noticed strange behaviour during 1st week 22-26 Nov -->
<!-- ```{r} -->
<!-- # First import pop_suc() function with specific period set -->
<!-- control <- pop_suc_okr2 (df_lead_pl, "2017-11-27", "2017-12-03", "rwd") -->
<!-- experiment <- pop_suc_okr2 (df_lead_pl_pwa, "2017-11-27", "2017-12-03", "rwd") -->
<!-- ``` -->


<!-- # Test dataset -->
<!-- ```{r cars} -->
<!-- popA <- control$pop -->
<!-- popB <- experiment$pop -->
<!-- sucA <- control$suc -->
<!-- sucB <- experiment$suc -->

<!-- dfOnboarding <- -->
<!--     data.frame( -->
<!--         id = c("01", "02"), -->
<!--         name = c("Original", "Variation with Onboarding"), -->
<!--         period = c("2nd week", "2nd week"), -->
<!--         PopulationMetric = c("new_users","new_users"), -->
<!--         PopulationValue = c(popA, popB), -->
<!--         SucessMetric = c("okr_2","okr_2"), -->
<!--         SucessValue = c(sucA, sucB) -->
<!--     ) -->

<!-- dfOnboarding$ctr <-  -->
<!--     dfOnboarding$SucessValue / dfOnboarding$PopulationValue -->
<!-- ``` -->

<!-- # Power analysis -->
<!-- ```{r} -->
<!-- testResultsOnboarding <-  -->
<!--     power.prop.test( -->
<!--         n = dfOnboarding$PopulationValue,  -->
<!--         p1 = dfOnboarding$ctr[1], -->
<!--         p2 = dfOnboarding$ctr[2], -->
<!--         sig.level = 0.05, -->
<!--         alternative = "two.sided" -->
<!--     ) -->

<!-- testResultsOnboarding -->
<!-- ``` -->


<!-- Variation is just -9% below original. Test has not enough power yet. -->
<!-- ```{r} -->
<!-- (testResultsOnboarding$p2 - testResultsOnboarding$p1) / testResultsOnboarding$p1 -->
<!-- ``` -->
